{% set name = "jd" %}
{% set version = "2.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/josephburnett/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: d1211397b92ca445dc65585ab6352a1977c7db37056a59be0dee0f0e11a7e2df

build:
  number: 0
  binary_relocation: false

requirements:
  build:
    - {{ compiler('go-nocgo') }}
    - go-licenses

test:
  commands:
    - jd --help

about:
  home: https://github.com/josephburnett/jd
  summary: JSON diff and patch
  license: MIT
  license_file:
    - LICENSE
    - library_licenses/

extra:
  recipe-maintainers:
    - danielnachun
    - moritzwilksch
