{% set name = "jd" %}
{% set version = "2.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/josephburnett/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: d9e2378c07be60ba42eb1a87e5b5c9eac9f0078b3643757a8d560e2690327c36

build:
  number: 0
  binary_relocation: false

requirements:
  build:
    - {{ compiler('go-nocgo') }}
    - go-licenses

test:
  commands:
    - jd --help

about:
  home: https://github.com/josephburnett/jd
  summary: JSON diff and patch
  license: MIT
  license_file:
    - LICENSE
    - library_licenses/

extra:
  recipe-maintainers:
    - danielnachun
    - moritzwilksch
